# Generated by Django 3.1.7 on 2021-12-08 09:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='adharcard',
            field=models.ImageField(default=' ', upload_to='media/images/adharcard'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='first_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='langitude_loc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='last_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='longitude_loc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='your_Address',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
