# Generated by Django 3.1.7 on 2021-12-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211208_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='postbyseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sellerpost'),
        ),
    ]
