# Generated by Django 3.1.7 on 2021-12-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211208_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='postbyseller',
        ),
        migrations.DeleteModel(
            name='sellerPost',
        ),
    ]
