# Generated by Django 3.1.7 on 2021-12-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211208_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
