# Generated by Django 3.1.7 on 2021-12-08 16:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serviceProvider',
            new_name='serviceProviderDetails',
        ),
        migrations.DeleteModel(
            name='buyer',
        ),
        migrations.DeleteModel(
            name='seller',
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
