# Generated by Django 3.1.7 on 2021-12-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ume', '0003_auto_20211208_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpost',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
